name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code (run actions/checkout@v3)
        uses: actions/checkout@v3

      - name: Setup Node.js (run actions/setup-node@v3)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set up environment variables
        run: |
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
          echo "TEST_MONGODB_URI=${{ secrets.TEST_MONGODB_URI }}" >> .env
          echo "SECRET=${{ secrets.SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      - name: npm install
        run: npm install

      - name: lint
        run: npm run eslint -- --fix

      - name: run integration tests
        run: npm run test

      - name: install playwright browsers
        run: npx playwright install --with-deps

      - name: run playwright e2e tests
        run: npm run test:e2e
