name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code (run actions/checkout@v3)
        uses: actions/checkout@v3

      - name: Setup Node.js (run actions/setup-node@v3)
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: npm install
        run: npm install

      - name: lint
        run: npm run eslint -- --fix --max-warnings=0

      - name: Run unit tests
        run: npm test

      - name: e2e tests
        run: npm run test:e2e

